// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoJJdvsO7dP6T0lYERdZbFWA1WAm0i_uM',
    appId: '1:413256586171:web:04d93cdcb7373819096a9e',
    messagingSenderId: '413256586171',
    projectId: 'irrifes-sensor',
    authDomain: 'irrifes-sensor.firebaseapp.com',
    storageBucket: 'irrifes-sensor.firebasestorage.app',
    measurementId: 'G-RK6DGR598W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8BVu0aeW3O4LqyJ1epfzy8Y4vw0JnBKs',
    appId: '1:413256586171:android:a6fbc0c8bf80d3c5096a9e',
    messagingSenderId: '413256586171',
    projectId: 'irrifes-sensor',
    storageBucket: 'irrifes-sensor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGWRfp8bA62jH0yv3xPyMM1q6QmAlTJ5I',
    appId: '1:413256586171:ios:19e7ed9bf7f22cb7096a9e',
    messagingSenderId: '413256586171',
    projectId: 'irrifes-sensor',
    storageBucket: 'irrifes-sensor.firebasestorage.app',
    iosBundleId: 'com.example.irrifesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGWRfp8bA62jH0yv3xPyMM1q6QmAlTJ5I',
    appId: '1:413256586171:ios:19e7ed9bf7f22cb7096a9e',
    messagingSenderId: '413256586171',
    projectId: 'irrifes-sensor',
    storageBucket: 'irrifes-sensor.firebasestorage.app',
    iosBundleId: 'com.example.irrifesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoJJdvsO7dP6T0lYERdZbFWA1WAm0i_uM',
    appId: '1:413256586171:web:8de50d6787a7f61f096a9e',
    messagingSenderId: '413256586171',
    projectId: 'irrifes-sensor',
    authDomain: 'irrifes-sensor.firebaseapp.com',
    storageBucket: 'irrifes-sensor.firebasestorage.app',
    measurementId: 'G-KZBB8HFGKW',
  );
}
